name: delete_old_packages

on:
  workflow_dispatch:

  push:
    branches:
      - containerized_stable

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  delete_old_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          delete-tags: '.*'
          delete-untagged: true
