name: rostest_unstable

on:

  workflow_dispatch:

  schedule:
    - cron:  '0 22 * * *' # every day at 00.00 UTC+2

jobs:

  init-artifacts:
    runs-on: ubuntu-20.04
    steps:
      - id: execute
        run: |
          mkdir -p /tmp/artifacts
          touch /tmp/artifacts/void
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: /tmp/artifacts/

  build-for-coverage:
    needs: init-artifacts
    runs-on: ubuntu-20.04
    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: /tmp/artifacts/
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - id: test
        run: |
          .ci/build_for_testing.sh /tmp/artifacts unstable
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: /tmp/artifacts/

  generate-jobs:
    needs: build-for-coverage
    runs-on: ubuntu-20.04
    outputs:
      packages: ${{ steps.generate.outputs.packages }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - id: generate
        run: |
          JOB_STRATEGY_MATRIX=$(./.ci/get_test_matrix.sh)
          echo "packages=$JOB_STRATEGY_MATRIX" >> "$GITHUB_OUTPUT"

  test-job:
    needs: generate-jobs
    runs-on: ubuntu-20.04
    timeout-minutes: 360 # 6 hour timeout
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJson(needs.generate-jobs.outputs.packages) }}
    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: /tmp/artifacts/
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ci_scripts
          ref: master
          path: .ci_scripts
          token: ${{ secrets.PUSH_TOKEN }}
      - id: test
        run: |
          .ci/test.sh "${{ matrix.job }}" /tmp/artifacts unstable
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: /tmp/artifacts/
