name: rostest_merge_to_release

on:
  workflow_call:
    secrets:
      PUSH_TOKEN:
        required: true

  workflow_dispatch:

  push:
    branches:
      - containerized_stable

jobs:

  init-artifacts:
    runs-on: ubuntu-22.04
    env:
      TOKEN: ${{ secrets.DOCKERHUB }}
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - id: prime_image
        run: |
          ./scripts/prime_image/prime_image.sh ctumrs/ros_noetic:2025-02-05 noetic_builder_${{ github.RUN_ID }} testing

  build-for-coverage:
    needs: init-artifacts
    env:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
    runs-on: ubuntu-22.04
    steps:
      - id: init_artifacts
        run: |
          mkdir -p /tmp/artifacts
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - id: test
        run: |
          ./scripts/build_for_testing/build.sh mrs testing noetic_builder_${{ github.RUN_ID }} /tmp/artifacts testing
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: /tmp/artifacts/
          overwrite: true

  generate-jobs:
    needs: build-for-coverage
    runs-on: ubuntu-22.04
    outputs:
      packages: ${{ steps.generate.outputs.packages }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - id: generate
        run: |
          JOB_STRATEGY_MATRIX=$(./scripts/get_test_matrix.sh mrs)
          echo "packages=$JOB_STRATEGY_MATRIX" >> "$GITHUB_OUTPUT"

  test-job:
    needs: generate-jobs
    runs-on: ubuntu-22.04
    timeout-minutes: 360 # 6 hour timeout
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJson(needs.generate-jobs.outputs.packages) }}
    env:
      TOKEN: ${{ secrets.DOCKERHUB }}
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Load artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifacts
          merge-multiple: true
          path: /tmp/artifacts/
      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ci_scripts
          ref: master
          path: .ci_scripts
          token: ${{ secrets.PUSH_TOKEN }}
      - id: build
        run: |
          ./scripts/ros_tests/run_tests.sh mrs unstable "${{ matrix.job }}" noetic_builder_${{ github.RUN_ID }} /tmp/artifacts
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: /tmp/artifacts/
          overwrite: true

  merge_and_push:
    runs-on: ubuntu-22.04
    needs: test-job
    env:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - id: merge
        run: |
          ./scripts/merge_push_to_release.sh

  publish_coverage:
      runs-on: ubuntu-22.04
      needs: test-job
      steps:
        - name: Load artifacts
          uses: actions/download-artifact@v4
          with:
            pattern: artifacts
            merge-multiple: true
            path: /tmp/artifacts/
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
            submodules: 'recursive'
        - id: test
          run: |
            ls -la /tmp/artifacts
            ./.ci/publish_coverage.sh /tmp/artifacts
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.PUSH_TOKEN }}
            publish_dir: /tmp/coverage_html
            allow_empty_commit: true
            force_orphan: true

  delete_builder:
    needs: test-job
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Delete current image
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: '${{ github.event.repository.name }}'
          delete-tags: 'noetic_builder_${{ github.RUN_ID }}'
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Delete old images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: '${{ github.event.repository.name }}'
          older-than: 7 days
          token: ${{ secrets.PUSH_TOKEN }}
