name: test

on:
  workflow_dispatch:

  push:
    branches:
      - "containerized"

env:
  arch: arm
  variant: unstable
  runs_on: ubuntu-24.04-${{ arch }}
  artifacts_folder: /tmp/artifacts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  init-artifacts:
    runs-on: ${{ runs_on }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - id: init_artifacts
        run: |
          mkdir -p ${{ artifacts_folder }}
          mkdir -p ${{ artifacts_folder }}/metarepositories
      - id: prime_image
        run: |
          ./.ci/prime_image/prime_image.sh
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ${{ artifacts_folder }}/
          overwrite: true

  generate-jobs:
    needs: init-artifacts
    runs-on: ${{ runs_on }}
    outputs:
      packages: ${{ steps.generate.outputs.packages }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ci_scripts
          ref: master
          path: .ci_scripts
          token: ${{ secrets.PUSH_TOKEN }}
      - id: generate
        run: |
          JOB_STRATEGY_MATRIX=$(./.ci/get_build_matrix.sh mrs ${{ variant }} ${{ arch }}64)
          cat /tmp/log.txt
          echo "packages=$JOB_STRATEGY_MATRIX" >> "$GITHUB_OUTPUT"

  build-job:
    needs: generate-jobs
    runs-on: ${{ runs_on }}
    timeout-minutes: 360 # 6 hour timeout
    strategy:
      matrix:
        job: ${{ fromJson(needs.generate-jobs.outputs.packages) }}
      max-parallel: 1 # Run jobs serially
    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifacts
          merge-multiple: true
          path: ${{ artifacts_folder }}/
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ci_scripts
          ref: master
          path: .ci_scripts
          token: ${{ secrets.PUSH_TOKEN }}
      - id: build
        run: |
          .ci/build.sh mrs ${{ variant }} "${{ matrix.job }}"
          ls ${{ artifacts_folder }}
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ${{ artifacts_folder }}/
          overwrite: true

  collect-artifacts:
    runs-on: ${{ runs_on }}
    needs: build-job
    env:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifacts
          merge-multiple: true
          path: ${{ artifacts_folder }}/
      - id: execute
        run: |
          rm ${{ artifacts_folder }}/builder.tar 2> /dev/null || true
          rm ${{ artifacts_folder }}/compiled.txt 2> /dev/null || true
          rm ${{ artifacts_folder }}/compile_further.txt 2> /dev/null || true
          rm ${{ artifacts_folder }}/base_sha.txt 2> /dev/null || true
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ci_scripts
          ref: master
          path: .ci_scripts
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Deploy
        run: .ci_scripts/package_build/push_to_ppa.sh ${{ variant }} ${{ artifacts_folder }}
