name: test_unstable

on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - containerized_stable

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  prime-image:
    runs-on: ubuntu-22.04
    env:
      TOKEN: ${{ secrets.DOCKERHUB }}
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ci_scripts
          ref: master
          path: ci_scripts
      - id: prime_image
        run: |
          ./ci_scripts/docker/prime_image_testing/prime_image.sh ctumrs/ros_noetic:2025-02-05 noetic_builder_${{ github.RUN_ID }} unstable /tmp/artifacts

  generate-jobs:
    needs: prime-image
    runs-on: ubuntu-22.04
    outputs:
      packages: ${{ steps.generate.outputs.packages }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - id: generate
        run: |
          JOB_STRATEGY_MATRIX=$(./scripts/get_test_matrix.sh mrs)
          echo "packages=$JOB_STRATEGY_MATRIX" >> "$GITHUB_OUTPUT"

  test-job:
    needs: generate-jobs
    runs-on: ubuntu-22.04
    timeout-minutes: 360 # 6 hour timeout
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJson(needs.generate-jobs.outputs.packages) }}
    env:
      TOKEN: ${{ secrets.DOCKERHUB }}
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ci_scripts
          ref: master
          path: ci_scripts
          token: ${{ secrets.PUSH_TOKEN }}
      - id: build
        run: |
          ./ci_scripts/ros_test/run_test.sh mrs unstable "${{ matrix.job }}" noetic_builder_${{ github.RUN_ID }} /tmp/artifacts

  delete_builder:
    needs: test-job
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Delete current image
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: '${{ github.event.repository.name }}'
          delete-tags: 'noetic_builder_${{ github.RUN_ID }}'
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Delete old images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: '${{ github.event.repository.name }}'
          older-than: 7 days
          token: ${{ secrets.PUSH_TOKEN }}
